# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  marvel: scoperetail/marvel@dev:e5011f7

workflows:
  build-and-test:
    jobs:
      - marvel/sonar-scan:
          context:
            - OSSRH
            - SLACK
            - ARTIFACTORY
            - SONAR
          filters:
            branches:
              ignore:
                - master
                - /HOTFIX-.*/
      - marvel/maven-deploy:
          context:
            - OSSRH
            - SLACK
            - ARTIFACTORY
          filters:
            branches:
              ignore:
                - master
                - /HOTFIX-.*/
      - marvel/maven-release-spring:
          context:
            - OSSRH
            - SLACK
            - ARTIFACTORY
          filters:
            branches:
              only:
                - master
                - /HOTFIX-.*/